"""empty message

Revision ID: 003176900687
Revises: d70d4ea8a985
Create Date: 2023-03-12 08:33:45.645379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003176900687'
down_revision = 'd70d4ea8a985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('literal', sa.String(length=3), nullable=False),
    sa.Column('numeric', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('sku',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('sku',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)

    op.drop_table('size')
    op.drop_table('color')
    # ### end Alembic commands ###
