"""empty message

Revision ID: 03abe5900e35
Revises: 996f068f546c
Create Date: 2023-03-11 13:01:43.181278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03abe5900e35'
down_revision = '996f068f546c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'product_image', ['image_id'], ['id'])

    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.drop_constraint('product_image_product_id_fkey', type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('product_image_product_id_fkey', 'product', ['product_id'], ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###
