"""empty message

Revision ID: 24446a5fd3ab
Revises: 890286c28f7a
Create Date: 2023-03-09 21:59:59.338267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24446a5fd3ab'
down_revision = '890286c28f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.Unicode(length=50), nullable=True))
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
