"""empty message

Revision ID: 890286c28f7a
Revises: 8c9a3fb7492f
Create Date: 2023-03-09 21:49:53.515359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890286c28f7a'
down_revision = '8c9a3fb7492f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.drop_column('image__file_name')
        batch_op.drop_column('image__ext')
        batch_op.drop_column('image__mime_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image__mime_type', sa.VARCHAR(length=1016), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image__ext', sa.VARCHAR(length=1010), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image__file_name', sa.VARCHAR(length=1016), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
