"""brand

Revision ID: 8c9a3fb7492f
Revises: 112544312349
Create Date: 2023-03-09 21:46:24.946399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c9a3fb7492f'
down_revision = '112544312349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.Unicode(length=128), nullable=True))
        batch_op.add_column(sa.Column('type', sa.Unicode(length=3), nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.Unicode(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.drop_column('file_name')
        batch_op.drop_column('type')
        batch_op.drop_column('path')

    # ### end Alembic commands ###
