"""empty message

Revision ID: 996f068f546c
Revises: e4b345cd3adf
Create Date: 2023-03-11 12:51:52.912752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996f068f546c'
down_revision = 'e4b345cd3adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editions', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_parent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('is_parent')
        batch_op.drop_column('editions')

    # ### end Alembic commands ###
