"""empty message

Revision ID: b7e39498ba88
Revises: 24446a5fd3ab
Create Date: 2023-03-09 22:42:42.229803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e39498ba88'
down_revision = '24446a5fd3ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.Unicode(length=128), nullable=True))
        batch_op.add_column(sa.Column('type', sa.Unicode(length=3), nullable=True))
        batch_op.add_column(sa.Column('name', sa.Unicode(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.drop_column('type')
        batch_op.drop_column('path')

    # ### end Alembic commands ###
