"""empty message

Revision ID: d4503515d044
Revises: 19c6fd1f81e8
Create Date: 2023-03-12 09:10:20.633654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4503515d044'
down_revision = '19c6fd1f81e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('editions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editions', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
